spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mapping: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true
    database: h2
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 9090
  servlet:
    context-path: /

logging:
  config: classpath:logback/logback-spring.xml